import type { Metadata } from "next";

/** Production URL — override via NEXT_PUBLIC_SITE_URL. Replace before launch. */
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://lihi-gilad.co.il";

const TITLE = "ליהיא שטויר גלעד | הפקת פודקאסטים לחברות וארגונים";
const DESCRIPTION =
  "שירות מלא להפקת פודקאסט מקצועי לחברות: אפיון, אסטרטגיה, כתיבת תוכן, ראיונות, צילום, הקלטה, עריכה ותוכן לרשתות. לחיזוק שיווק, מיתוג, תקשורת פנים וגאוות עובדים.";

export const siteMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s | ליהיא שטויר גלעד",
  },
  description: DESCRIPTION,
  applicationName: "ליהיא שטויר גלעד — פודקאסטים לחברות",
  authors: [{ name: "ליהיא שטויר גלעד" }],
  creator: "ליהיא שטויר גלעד",
  keywords: [
    "פודקאסט לחברות",
    "פודקאסט ארגוני",
    "הפקת פודקאסטים",
    "פודקאסט תאגידי",
    "תקשורת פנים ארגונית",
    "מיתוג מעסיק",
    "סטוריטלינג ארגוני",
    "פודקאסט וידאו",
    "ליהיא שטויר גלעד",
    "תוכן לרשתות חברתיות",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "he_IL",
    url: SITE_URL,
    siteName: "ליהיא שטויר גלעד — פודקאסטים לחברות",
    title: TITLE,
    description: DESCRIPTION,
    // og:image is generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  category: "business",
};
