import type { Metadata } from "next";

/** Fallback production URL when NEXT_PUBLIC_SITE_URL is unset or unusable. */
const DEFAULT_SITE_URL = "https://www.gilead.co.il";

/**
 * Production URL — override via NEXT_PUBLIC_SITE_URL.
 *
 * Hardened so the metadataBase `new URL(SITE_URL)` can never throw at build
 * time (an invalid value previously failed page-data collection for
 * /_not-found and broke the whole build):
 * - A bare host (e.g. "gilead.co.il", as the deploy platform sets it) gets
 *   https:// prepended.
 * - Trailing slashes are stripped.
 * - An empty, whitespace-only, or malformed value falls back to the default.
 *   (`??` alone does not catch an empty string, which `new URL` rejects.)
 */
function resolveSiteUrl(): string {
  const candidate =
    process.env.NEXT_PUBLIC_SITE_URL?.trim() || DEFAULT_SITE_URL;
  const withScheme = /^https?:\/\//i.test(candidate)
    ? candidate
    : `https://${candidate}`;
  try {
    // Constructing the URL validates and normalizes it in one step.
    return new URL(withScheme).toString().replace(/\/+$/, "");
  } catch {
    return DEFAULT_SITE_URL;
  }
}

export const SITE_URL = resolveSiteUrl();

const TITLE = "ליהיא שטויאר גלעד | הפקת פודקאסטים לחברות וארגונים";
const DESCRIPTION =
  "שירות מלא להפקת פודקאסט מקצועי לחברות: אפיון, אסטרטגיה, כתיבת תוכן, ראיונות, צילום, הקלטה, עריכה ותוכן לרשתות. לחיזוק שיווק, מיתוג, תקשורת פנים וגאוות עובדים.";

export const siteMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s | ליהיא שטויאר גלעד",
  },
  description: DESCRIPTION,
  applicationName: "ליהיא שטויאר גלעד — פודקאסטים לחברות",
  authors: [{ name: "ליהיא שטויאר גלעד" }],
  creator: "ליהיא שטויאר גלעד",
  keywords: [
    "פודקאסט לחברות",
    "פודקאסט ארגוני",
    "הפקת פודקאסטים",
    "פודקאסט תאגידי",
    "תקשורת פנים ארגונית",
    "מיתוג מעסיק",
    "סטוריטלינג ארגוני",
    "פודקאסט וידאו",
    "ליהיא שטויאר גלעד",
    "תוכן לרשתות חברתיות",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "he_IL",
    url: SITE_URL,
    siteName: "ליהיא שטויאר גלעד — פודקאסטים לחברות",
    title: TITLE,
    description: DESCRIPTION,
    // og:image is generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  category: "business",
};
